name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 
      
      - name: Terbium commit hash
        uses: mathiasvr/command-output@v1
        id: terbium_commit
        with:
          run: git ls-remote https://github.com/TerbiumLang/Terbium HEAD | awk '{ print $1}'

      - name: Build wasm
        run: wasm-pack build --target web --release
    
      - name: Create build folder
        run: mkdir build
      
      - name: Copy files to build
        run: cp site/* build && cp pkg/* build
      
      - name: List build dir
        run: ls build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: terbium_playground_wasm
          path: build/terbium_playground_bg.wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          commit_message: "Deploy: Terbium Commit: ${{ steps.terbium_commit.outputs.stdout }} Repo Commit:"
